name: Test

on: [push]

jobs:
  build:
    runs:
      using: 'docker'
      image: 'Dockerfile'
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Rake
      run: |
        bundle exec rails test

