name: Test

on: [push]

runs:
  using: 'docker'
  image: 'Dockerfile'

jobs:
  build:
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Rake
      run: |
        bundle exec rails test

